
FROM ubuntu:latest
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk wget && \
    wget -q https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz && \
    tar -xzf spark-3.5.0-bin-hadoop3.tgz && \
    mv spark-3.5.0-bin-hadoop3 /opt/spark

ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

EXPOSE 7077 8080

ENTRYPOINT ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]